name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: rm13rotem/myapp

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      - name: Slack Success Notification
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text":"✅ Build succeeded for repository `${{ github.repository }}` on branch `${{ github.ref_name }}`"
          }' \
          ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Failure Notification
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text":"❌ Build FAILED for repository `${{ github.repository }}` on branch `${{ github.ref_name }}`"
          }' \
          ${{ secrets.SLACK_WEBHOOK }}
