name: hello-actions

on:
  push:
  workflow_dispatch: 

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello GitHub Actions"
        
  build:
    runs-on: ubuntu-latest
    needs: [ hello ]
    steps:
      - name: Print message
        run: echo "build image"

  marketplace:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: Print message
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Github actions student"

  show-secret:
    runs-on: ubuntu-latest
    environment: production
    needs: hello
    steps:
      - name: Print Variable
        run: echo ${{ vars.JB_DEMO_USER }}
      - name: Print Secret
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}

  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: docker build -t docker.io/rm13rotem/devops_4:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'docker.io/rm13rotem/devops_4:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
